gitlab:
  image: quay.io/redhat-gpte/gitlab:17.4.1
  email:
    address: "gitlab@rhdemo.com"
    displayName: "GitLab Admin"
    replyTo: "noreply@rhdemo.com"
  smtp:
    enabled: "false"
    domain: "rhdemo.com"
    host:
    port: "587"
    user: "gitlab"
    password: "gitlab"
  ssh:
    host:
    port: "22"
  rootPassword:
  host:
  https: "true"
  rootEmail: "root@rhdemo.com"
  keyBase:
    db: "0123456789"
    otp: "0123456789"
    secret: "0123456789"
  users:
    users:
      - id: dev1
      - id: dev2
      - id: pe1
      - id: pe2
    password: 
  groups:
    - name: rhdh
      repo:
        - name: template-quarkus-simple
          url: https://github.com/btison/rhdh-template-quarkus-simple.git
      users:
        - id: pe1
        - id: pe2
    - name: devteam1
      repo: []
      users:
        - id: dev1
        - id: dev2
    - name: parasol
      repo:
        - name: parasol-store
          url: https://github.com/btison/pew-parasol-store.git
        - name: parasol-web
          url: https://github.com/btison/pew-parasol-web.git
        - name: parasol-db-manifests
          url: https://github.com/btison/pew-parasol-db-manifests.git
        - name: parasol-store-manifests
          url: https://github.com/btison/pew-parasol-store-manifests.git
        - name: parasol-web-manifests
          url: https://github.com/btison/pew-parasol-web-manifests.git
        - name: parasol-store-build-manifests
          url: https://github.com/btison/pew-parasol-store-build-manifests.git
      users:
        - id: dev1
        - id: dev2
  templates:
    - group: rhdh
      project: template-quarkus-simple
      branch: main
      templates:
        - template.yaml

postgresql:
  dbUser: gitlab
  dbPassword: passw0rd
  dbName: gitlab_production

cluster:
  subdomain: 

gitops:
  namespace:
  project: default

quay:
  host: 

vault:
  name: vault
  namespace: vault